### ISSUE TITLE
Part 2 - Question 2

### ISSUE THREAD

**Issue by ocnrandolph** [nss-data-science-cohort-4/dq3-earthquakes-valkyries-dq3#19]
Do the magnitudes of earthquakes seem to follow the distribution described by Nate Silver. That is, one higher magnitude is ten times less likely to occur?
     - [ ] Conduct analyses to answer the question: do magnitudes for earthquakes in TN follow a power law distribution?

**Comment by dailyp** [comment]
Refer to notebook, "usgs_api_patti_logs". 
Result: neither histogram nor qq-plot appears to indicate that applying log transformation shows that every unit increase change in magnitude reflects a lower occurence. This is because applying a log transformation causes the data to follow a more normal distribution.

The original histogram of the usgs_tn['mag'] is the best reflection of the distribution described by Nate Silver, after the median of 1.6 magnitude.  So in effect, after 1.6 median, each incremental increase in magnitude does show a reflective decrease in activity. 

The ramp-up on the smaller magnitudes before the 1.6 median (which conflicts with Nate Silver's analysis) may be due to an increased monitoring over time.

**Comment by dailyp** [comment]
See comment above.  This issue is closed.
